# Generated by Django 4.1.5 on 2023-01-17 15:30

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMALL', 'SMALL'), ('BIG', 'BIG')], max_length=100)),
                ('color', models.CharField(max_length=200)),
                ('lenght', models.DecimalField(decimal_places=10, max_digits=20)),
                ('load_valume', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.DecimalField(decimal_places=10, max_digits=20)),
                ('geom', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
        migrations.CreateModel(
            name='TollStaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('toll_per_cross', models.IntegerField()),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('national_code', models.IntegerField()),
                ('age', models.IntegerField()),
                ('total_toll_paid', models.IntegerField()),
                ('ownerCar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.car')),
            ],
        ),
    ]
