# Generated by Django 4.1.5 on 2023-01-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0003_traffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='width',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
