# Generated by Django 4.1.5 on 2023-01-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0004_alter_road_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('toll_per_cross', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.car')),
                ('toll_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.tollstaion')),
            ],
        ),
    ]
