# Generated by Django 4.1.5 on 2023-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toll', '0005_toll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollstaion',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
